import { Head } from "@chakra-ui/react";

const Header = () => {
  return (
    <Head>
      <title>Bounty Hunter DAO</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Header;